In [2]:
import numpy as np

# 切片

In [9]:
# 轴的个数=维度;轴3个，轴0=2；轴1=2，轴2=4
a=np.random.randn(2,2,3)
a

array([[[ 0.77961319, -0.41480911, -0.735299  ],
        [-0.69566619, -0.49892154,  0.24072569]],

       [[ 0.1511517 , -0.2328418 , -0.66584352],
        [ 2.86398683,  1.91751101,  0.98364049]]])

In [11]:
# 轴之间的切片，以逗号分隔；从m->n,以冒号分隔
# 提取轴0=0，轴1=1，轴2=1，2
a[0,1,1:3]

array([-0.49892154,  0.24072569])

# bool 切片

In [12]:
a=np.random.randn(2,3)
a

array([[-0.02212786, -0.41932114, -0.81272425],
       [ 0.93947391, -1.05794296,  0.03980845]])

In [13]:
# bool 切片，长度必须同轴一样
a[[True,False],[True,True,False]]

array([-0.02212786, -0.41932114])

In [14]:
# 提取第1行第2，3列
a[[0],[1,2]]

array([-0.41932114, -0.81272425])

In [15]:
a[[0]]==a[0]

array([[ True,  True,  True]])